# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: FOIA request prototype
description: > # this means to ignore newlines until "baseurl:"
  A prototype exploring how the public might submit a FOIA request through
  a single national portal.
baseurl: "" # the subpath of your site, e.g. /blog
agency:
  name: Office of Information Policy
  email: info@agency.gov

# Build settings
#
# You probably don't change these unless you know what you're doing :)
markdown: kramdown
keep_files:
  - assets/fonts
  - assets/img
  - assets/vendor
  - assets/js
exclude:
  - bin
  - node_modules
  - npm-debug.log
  - package.json
  - README.md
  - src
